default:
  tags:
    - local

stages:
  - test
  - build

include:
  - project: 'coldforge/ci-templates'
    ref: main
    file: '/templates/kaniko-build.yml'

.go-cache: &go-cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go/pkg/mod/
    policy: pull-push

test:unit:
  stage: test
  image: golang:1.25-alpine
  <<: *go-cache
  variables:
    GOPATH: ${CI_PROJECT_DIR}/.go
    CGO_ENABLED: "1"
  before_script:
    - for i in 1 2 3 4 5; do apk add --no-cache git ca-certificates build-base && break || echo "Attempt $i failed, retrying in 5s..." && sleep 5; done
    - mkdir -p .go
  script:
    - go mod tidy
    - go test -v -race -cover ./internal/...
  coverage: '/coverage: \d+\.\d+% of statements/'

lint:
  stage: test
  image: golang:1.25-alpine
  <<: *go-cache
  variables:
    GOPATH: ${CI_PROJECT_DIR}/.go
  before_script:
    - for i in 1 2 3 4 5; do apk add --no-cache git ca-certificates curl && break || echo "Attempt $i failed, retrying in 5s..." && sleep 5; done
    - mkdir -p .go
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.11.2
    - go mod tidy
  script:
    - ${GOPATH}/bin/golangci-lint run --timeout 5m ./...
  allow_failure: true

build:relay:
  extends: .kaniko-build
  stage: build

build:admin:
  extends: .kaniko-build
  stage: build
  variables:
    KANIKO_DOCKERFILE_SUBPATH: "/Dockerfile.admin"
    KANIKO_IMAGE: "$CI_REGISTRY_IMAGE/admin"
